export const loginusernameInput = "//input[@name='username']";
export const loginpasswordInput = "//input[@name='password']";
export const loginButton = "//button[normalize-space()='Login']";
export const btnGraph = "//*[contains(text(),'Graph')]/parent::a";
export const txtPrice = "//*[contains(text(),'Pricing')]";
export const btnselectCustomer = "//*[contains(text(),'Select customer')]/../parent::span";
export const listBoxGeneral = "//*[@role='listbox']/*[@role='option']/span";
export const txtDashBoard = "//h6[normalize-space()='Dashboard']";
export const recordName = "//a[contains(text(),'%s')]";
export const tableviewIcon = "//a[contains(text(),'%s')]/../following-sibling::td//i[@class='unhide icon']/parent::button";
export const tableeditIcon = "//a[contains(text(),'%s')]/../following-sibling::td//i[@class='edit icon']/parent::button";
export const tablecallIcon = "//a[contains(text(),'%s')]/../following-sibling::td//i[@class='call icon']/parent::button";
export const tableDeleteIcon = "//a[contains(text(),'%s')]/../following-sibling::td//i[@class='trash icon']/parent::button";
export const tablecheckbox = "//a[contains(text(),'%s')]//ancestor::tr//input[@type='checkbox']";
export const popUpOperation = "//div[@class='ui page modals dimmer transition visible active']//button[text()='%s']";
export const popUpHeader = "//div[@class='ui page modals dimmer transition visible active']//div[@class='header' and text()='%s']";
export const lnkLeftPaneEntityName = "//div[@id='main-nav']//span[text()='%s']";
export const pageVerificationName = "//span[@class = 'selectable ' and text()='%s']";
export const listDropDown = "//div[@class='visible menu transition']/div[@role='option']";
export const listDropDown1 = "//div[@class='visible menu transition']/div[@role='option']/span";
export const listSearchCombox = "//div[@role='listbox' and @class='visible menu transition']/div[@role='option']";
export const btnSave = "//button[contains(text(),'Save') and @class='ui linkedin button']";
export const btnCreate = "//button[contains(text(),'Create') and @class='ui linkedin button']";
export const btnTopHeaderMenuSettings = "//body/div[@id='ui']/div[@class='ui fluid container']/div[@class='ui fluid container']/div[@id='top-header-menu']/div[@class='right menu']/div[@class='ui buttons']/div[@role='listbox']/i[@class='settings icon']";
export const lnkHome = ".home.icon";